import librecoin

def main(lc:librecoin):
    lc.display().table(0,0,16,3)
    lc.display().print("M1:   Menu 1", 2, 1)
    lc.keyboard().press("M1", "lc.view().set('views.menu_1')")
    lc.display().table(15,0,16,3)
    lc.display().print(" M2:   Menu 2 ", 16, 1)
    # lc.keyboard().press("M2", lc.display().view("screen_menu_2"))
    lc.display().table(30,0,16,3)
    lc.display().print(" M3:   Menu 3 ", 31, 1)
    # lc.keyboard().press("M2", lc.display().view("screen_menu_3"))
    lc.display().table(45,0,16,3)
    lc.display().print(" M4:   Menu 4 ", 46, 1)
    # lc.keyboard().press("M2", lc.display().view("screen_menu_4"))
    lc.display().table(60,0,16,3)
    lc.display().print(" M5:   Menu 5 ", 61, 1)
    # lc.keyboard().press("M2", lc.display().view("screen_menu_5"))
    lc.display().table(75,0,16,3)
    lc.display().print(" M6:   Menu 6 ", 76, 1)
    # lc.keyboard().press("M2", lc.display().view("screen_menu_6"))
    lc.display().table(90,0,16,3)
    lc.display().print(" M7:   Menu 7 ", 91, 1)
    # lc.keyboard().press("M2", lc.display().view("screen_menu_7"))
    lc.display().table(105,0,16,3)
    lc.display().print(" M8:   Menu 8 ", 106, 1)
    # lc.keyboard().press("M2", lc.display().view("screen_menu_8"))
    lc.display().table(120,0,16,3)
    lc.display().print(" M9:   Menu 9 ", 121, 1)
    # lc.keyboard().press("M2", lc.display().view("screen_menu_9"))
    lc.display().table(-16,0,16,3)
    lc.display().print(" MQ:     Quit ", -15, 1)
    lc.keyboard().press("MQ", "lc.quit()")
